/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

public class MainView extends javax.swing.JFrame {

    public Statement stmt;
    public ResultSet rs;
    Connection con = koneksi.KoneksiDatabase.bukaKoneksi();

    public MainView() {
        initComponents();

        lblNamauser.setText(Register.nama1);

        setVisible(true);
        setResizable(false);
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);

        TampilData();
    }

    private void Bersih() {
        edtNim.setText("");
        edtNamapeminjam.setText("");
        edtTanggal.setText("");
        edtPukul.setText("");
        edtRuangan.setText("");
        edtNamakegiatan.setText("");

        btnSimpan.setText("Simpan");
        edtNim.setEditable(true);
    }

    private void CariData() {
        try {
            stmt = con.createStatement();
            rs = stmt.executeQuery("SELECT * FROM ruangan WHERE "
                    + cmbCari.getSelectedItem().toString()
                    + " LIKE '%" + edtCari.getText() + "%'");

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("No.");
            model.addColumn("nim");
            model.addColumn("namapeminjam");
            model.addColumn("tanggal");
            model.addColumn("pukul");
            model.addColumn("ruangan");
            model.addColumn("kegiatan");

            int no = 1;

            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);

            while (rs.next()) {
                Object[] data = {
                    no++,
                    rs.getString("nim"),
                    rs.getString("namapeminjam"),
                    rs.getString("tanggal"),
                    rs.getString("pukul"),
                    rs.getString("ruangan"),
                    rs.getString("kegiatan")
                };
                model.addRow(data);
                tblData.setModel(model);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void TampilData() {
        try {
            stmt = con.createStatement();
            rs = stmt.executeQuery("SELECT * FROM ruangan");

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("No.");
            model.addColumn("nim");
            model.addColumn("namapeminjam");
            model.addColumn("tanggal");
            model.addColumn("pukul");
            model.addColumn("ruangan");
            model.addColumn("kegiatan");

            int no = 1;

            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);

            while (rs.next()) {
                Object[] data = {
                    no++,
                    rs.getString("nim"),
                    rs.getString("namapeminjam"),
                    rs.getString("tanggal"),
                    rs.getString("pukul"),
                    rs.getString("ruangan"),
                    rs.getString("kegiatan")
                };
                model.addRow(data);
                tblData.setModel(model);
            }

        } catch (Exception e) {
        }
    }

    /**
     * Creates new form MainView
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPaanel = new javax.swing.JPanel();
        SPOI = new javax.swing.JLabel();
        Version1 = new javax.swing.JLabel();
        SelamatDatang = new javax.swing.JLabel();
        lblNamauser = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        judul2 = new javax.swing.JLabel();
        btnRuangan = new javax.swing.JButton();
        btnPeralatan = new javax.swing.JButton();
        btnBarang = new javax.swing.JButton();
        btnList = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        ruanganPanel = new javax.swing.JPanel();
        judulRuangan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        edtNim = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        edtNamapeminjam = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edtPukul = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edtRuangan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edtNamakegiatan = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        cmbCari = new javax.swing.JComboBox<>();
        edtCari = new javax.swing.JTextField();
        edtTanggal = new javax.swing.JTextField();
        peralatanPanel = new javax.swing.JPanel();
        judulPeralatan = new javax.swing.JLabel();
        barangPanel = new javax.swing.JPanel();
        judulBarang = new javax.swing.JLabel();
        checklistPanel = new javax.swing.JPanel();
        judulChecklist = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HALAMAN MENU\n");
        setResizable(false);

        bodyPaanel.setBackground(new java.awt.Color(214, 48, 49));
        bodyPaanel.setPreferredSize(new java.awt.Dimension(758, 535));
        bodyPaanel.setRequestFocusEnabled(false);

        SPOI.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        SPOI.setForeground(new java.awt.Color(255, 255, 255));
        SPOI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SPOI.setText("SPOI");

        Version1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Version1.setForeground(new java.awt.Color(255, 255, 255));
        Version1.setText("Version 1.0");

        SelamatDatang.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        SelamatDatang.setForeground(new java.awt.Color(255, 255, 255));
        SelamatDatang.setText("Selamat Datang");

        lblNamauser.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblNamauser.setForeground(new java.awt.Color(255, 255, 255));

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        menuPanel.setPreferredSize(new java.awt.Dimension(153, 462));

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconInstiki1.jpg"))); // NOI18N

        judul1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        judul1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul1.setText("Sistem Peminjaman");

        judul2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        judul2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul2.setText("Operasional INSTIKI");

        btnRuangan.setBackground(new java.awt.Color(255, 255, 255));
        btnRuangan.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        btnRuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconRuangan.png"))); // NOI18N
        btnRuangan.setText("Ruangan");
        btnRuangan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRuangan.setIconTextGap(10);
        btnRuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRuanganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRuanganMouseExited(evt);
            }
        });
        btnRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRuanganActionPerformed(evt);
            }
        });

        btnPeralatan.setBackground(new java.awt.Color(255, 255, 255));
        btnPeralatan.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        btnPeralatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconPeralatan.png"))); // NOI18N
        btnPeralatan.setText("Peralatan");
        btnPeralatan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPeralatan.setIconTextGap(10);
        btnPeralatan.setMaximumSize(new java.awt.Dimension(123, 45));
        btnPeralatan.setMinimumSize(new java.awt.Dimension(123, 45));
        btnPeralatan.setPreferredSize(new java.awt.Dimension(123, 45));
        btnPeralatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPeralatanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPeralatanMouseExited(evt);
            }
        });
        btnPeralatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeralatanActionPerformed(evt);
            }
        });

        btnBarang.setBackground(new java.awt.Color(255, 255, 255));
        btnBarang.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        btnBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconBarang.png"))); // NOI18N
        btnBarang.setText("Barang");
        btnBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBarang.setIconTextGap(10);
        btnBarang.setMaximumSize(new java.awt.Dimension(123, 45));
        btnBarang.setMinimumSize(new java.awt.Dimension(123, 45));
        btnBarang.setPreferredSize(new java.awt.Dimension(123, 45));
        btnBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBarangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBarangMouseExited(evt);
            }
        });
        btnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangActionPerformed(evt);
            }
        });

        btnList.setBackground(new java.awt.Color(255, 255, 255));
        btnList.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        btnList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconChecklist_1.png"))); // NOI18N
        btnList.setText("Checklist");
        btnList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnList.setIconTextGap(10);
        btnList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListMouseExited(evt);
            }
        });
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconLogout.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setIconTextGap(10);
        btnLogout.setMaximumSize(new java.awt.Dimension(123, 45));
        btnLogout.setMinimumSize(new java.awt.Dimension(123, 45));
        btnLogout.setPreferredSize(new java.awt.Dimension(123, 45));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPeralatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(judul1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(judul2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judul1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judul2)
                .addGap(30, 30, 30)
                .addComponent(btnRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPeralatan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        mainPanel.setPreferredSize(new java.awt.Dimension(579, 513));
        mainPanel.setLayout(new java.awt.CardLayout());

        ruanganPanel.setBackground(new java.awt.Color(255, 255, 255));

        judulRuangan.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        judulRuangan.setText("PEMINJAMAN RUANGAN INSTIKI");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("NIM");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setText("Nama Peminjam");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Hari/ Tanggal");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Pukul");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Ruangan");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Kegiatan");

        btnSimpan.setText("SIMPAN");
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setText("BATAL");
        btnBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        tblData.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama Peminjam", "Hari/Tanggal", "Pukul", "Ruangan", "Kegiatan"
            }
        ));
        tblData.setAutoscrolls(false);
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        tblData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblDataKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);
        tblData.getAccessibleContext().setAccessibleDescription("");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("CARI DATA");

        cmbCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIM", "Tanggal", "Kegiatan" }));

        edtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCariKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout ruanganPanelLayout = new javax.swing.GroupLayout(ruanganPanel);
        ruanganPanel.setLayout(ruanganPanelLayout);
        ruanganPanelLayout.setHorizontalGroup(
            ruanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ruanganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ruanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                    .addGroup(ruanganPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ruanganPanelLayout.createSequentialGroup()
                        .addGroup(ruanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ruanganPanelLayout.createSequentialGroup()
                                .addGroup(ruanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                                .addGroup(ruanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ruanganPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(edtNamapeminjam))
                                    .addGroup(ruanganPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(ruanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(edtNamakegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(ruanganPanelLayout.createSequentialGroup()
                                                .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(ruanganPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(ruanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(edtTanggal, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(edtPukul)))))
                            .addComponent(judulRuangan)
                            .addGroup(ruanganPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ruanganPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edtRuangan)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ruanganPanelLayout.setVerticalGroup(
            ruanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ruanganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulRuangan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ruanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(edtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(ruanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edtNamapeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(ruanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ruanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ruanganPanelLayout.createSequentialGroup()
                        .addComponent(edtPukul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ruanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ruanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(edtNamakegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ruanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBatal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ruanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtCari))
                .addGap(79, 79, 79))
        );

        mainPanel.add(ruanganPanel, "card2");

        peralatanPanel.setBackground(new java.awt.Color(255, 255, 255));

        judulPeralatan.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        judulPeralatan.setText("PEMINJAMAN PERALATAN INSTIKI");

        javax.swing.GroupLayout peralatanPanelLayout = new javax.swing.GroupLayout(peralatanPanel);
        peralatanPanel.setLayout(peralatanPanelLayout);
        peralatanPanelLayout.setHorizontalGroup(
            peralatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peralatanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulPeralatan)
                .addContainerGap(275, Short.MAX_VALUE))
        );
        peralatanPanelLayout.setVerticalGroup(
            peralatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peralatanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulPeralatan)
                .addContainerGap(415, Short.MAX_VALUE))
        );

        mainPanel.add(peralatanPanel, "card3");

        barangPanel.setBackground(new java.awt.Color(255, 255, 255));

        judulBarang.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        judulBarang.setText("PEMINJAMAN BARANG INSTIKI");

        javax.swing.GroupLayout barangPanelLayout = new javax.swing.GroupLayout(barangPanel);
        barangPanel.setLayout(barangPanelLayout);
        barangPanelLayout.setHorizontalGroup(
            barangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barangPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulBarang)
                .addContainerGap(298, Short.MAX_VALUE))
        );
        barangPanelLayout.setVerticalGroup(
            barangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barangPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulBarang)
                .addContainerGap(415, Short.MAX_VALUE))
        );

        mainPanel.add(barangPanel, "card4");

        checklistPanel.setBackground(new java.awt.Color(255, 255, 255));

        judulChecklist.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        judulChecklist.setText("CHECKLIST");

        javax.swing.GroupLayout checklistPanelLayout = new javax.swing.GroupLayout(checklistPanel);
        checklistPanel.setLayout(checklistPanelLayout);
        checklistPanelLayout.setHorizontalGroup(
            checklistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checklistPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulChecklist)
                .addContainerGap(465, Short.MAX_VALUE))
        );
        checklistPanelLayout.setVerticalGroup(
            checklistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checklistPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulChecklist)
                .addContainerGap(415, Short.MAX_VALUE))
        );

        mainPanel.add(checklistPanel, "card5");

        javax.swing.GroupLayout bodyPaanelLayout = new javax.swing.GroupLayout(bodyPaanel);
        bodyPaanel.setLayout(bodyPaanelLayout);
        bodyPaanelLayout.setHorizontalGroup(
            bodyPaanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPaanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPaanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPaanelLayout.createSequentialGroup()
                        .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE))
                    .addGroup(bodyPaanelLayout.createSequentialGroup()
                        .addComponent(SPOI, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SelamatDatang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNamauser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                        .addComponent(Version1)))
                .addContainerGap())
        );
        bodyPaanelLayout.setVerticalGroup(
            bodyPaanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPaanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPaanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SPOI)
                    .addComponent(Version1)
                    .addComponent(SelamatDatang)
                    .addComponent(lblNamauser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPaanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 453, Short.MAX_VALUE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bodyPaanel, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPaanel, javax.swing.GroupLayout.PREFERRED_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRuanganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRuanganMouseEntered
        // TODO add your handling code here:
        btnRuangan.setBackground(new Color(235, 77, 75));
    }//GEN-LAST:event_btnRuanganMouseEntered

    private void btnRuanganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRuanganMouseExited
        // TODO add your handling code here:
        btnRuangan.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnRuanganMouseExited

    private void btnBarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarangMouseEntered
        // TODO add your handling code here:
        btnBarang.setBackground(new Color(235, 77, 75));
    }//GEN-LAST:event_btnBarangMouseEntered

    private void btnBarangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarangMouseExited
        // TODO add your handling code here:
        btnBarang.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnBarangMouseExited

    private void btnPeralatanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeralatanMouseEntered
        // TODO add your handling code here:
        btnPeralatan.setBackground(new Color(235, 77, 75));
    }//GEN-LAST:event_btnPeralatanMouseEntered

    private void btnPeralatanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeralatanMouseExited
        // TODO add your handling code here:
        btnPeralatan.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnPeralatanMouseExited

    private void btnListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListMouseEntered
        // TODO add your handling code here:
        btnList.setBackground(new Color(235, 77, 75));
    }//GEN-LAST:event_btnListMouseEntered

    private void btnListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListMouseExited
        // TODO add your handling code here:
        btnList.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnListMouseExited

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setBackground(new Color(235, 77, 75));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRuanganActionPerformed
        // TODO add your handling code here:

        // remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // add panel
        mainPanel.add(ruanganPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnRuanganActionPerformed

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangActionPerformed
        // TODO add your handling code here:

        // remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // add panel
        mainPanel.add(barangPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnBarangActionPerformed

    private void btnPeralatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeralatanActionPerformed
        // TODO add your handling code here:

        // remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // add panel
        mainPanel.add(peralatanPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnPeralatanActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        // TODO add your handling code here:

        // remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // add panel
        mainPanel.add(checklistPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnListActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:

        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda Yakin Akan Keluar?", "PERINGATAN", dialogBtn);

        if (dialogResult == 0) {
            // true condition
            System.exit(0);
        } else {
            // false condition
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
            stmt = con.createStatement();
            if (edtNim.getText().equals("")
                    || edtNamapeminjam.getText().equals("")
                    || edtTanggal.getText().equals("")
                    || edtPukul.getText().equals("")
                    || edtRuangan.getText().equals("")
                    || edtNamakegiatan.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong", "Validasi Data", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            // Aksi Simpan Data
            if (btnSimpan.getText() == "SIMPAN") {
                String cek = "SELECT * FROM ruangan WHERE nim = '" + edtNim.getText() + "'";
                rs = stmt.executeQuery(cek);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Ups.. NIM sudah ada");
                    return;
                } else {
                
                String sql = "INSERT INTO ruangan VALUES ('" + edtNim.getText()
                        + "','" + edtNamapeminjam.getText()
                        + "','" + edtTanggal.getText()
                        + "','" + edtPukul.getText()
                        + "','" + edtRuangan.getText()
                        + "','" + edtNamakegiatan.getText() + "')";
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                Bersih();
                TampilData();
                }
            } else {
                // Aksi Ubah Data
                String update = "UPDATE ruangan SET namapeminjam = '" + edtNamapeminjam.getText()
                        + "', tanggal = '" + edtTanggal.getText()
                        + "', pukul = '" + edtPukul.getText()
                        + "', ruangan = '" + edtRuangan.getText()
                        + "', kegiatan = '" + edtNamakegiatan.getText()
                        + "' WHERE nim = '" + edtNim.getText() + "'";
                stmt.executeUpdate(update);
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                Bersih();
                TampilData();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        // TODO add your handling code here:
        edtNim.setText(tblData.getValueAt(tblData.getSelectedRow(), 1).toString());
        edtNamapeminjam.setText(tblData.getValueAt(tblData.getSelectedRow(), 2).toString());
        edtTanggal.setText(tblData.getValueAt(tblData.getSelectedRow(), 3).toString());
        edtPukul.setText(tblData.getValueAt(tblData.getSelectedRow(), 4).toString());
        edtRuangan.setText(tblData.getValueAt(tblData.getSelectedRow(), 5).toString());
        edtNamakegiatan.setText(tblData.getValueAt(tblData.getSelectedRow(), 6).toString());

        edtNim.setEditable(false);
        btnSimpan.setText("Ubah");
    }//GEN-LAST:event_tblDataMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if (edtNamapeminjam.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih data yang akan dihapus !");
        } else {
            int jawab = JOptionPane.showConfirmDialog(null, "Data ini akan dihapus, lanjutkan ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (jawab == 0) {
                try {
                    stmt = con.createStatement();
                    String sql = "DELETE FROM ruangan WHERE namapeminjam = '" + edtNamapeminjam.getText() + "'";
                    stmt.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    TampilData();
                    Bersih();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        Bersih();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void edtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCariKeyPressed
        // TODO add your handling code here:
        CariData();
    }//GEN-LAST:event_edtCariKeyPressed

    private void tblDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDataKeyPressed
        // TODO add your handling code here:
        edtNim.setText(tblData.getValueAt(tblData.getSelectedRow(), 1).toString());
        edtNamapeminjam.setText(tblData.getValueAt(tblData.getSelectedRow(), 2).toString());
        edtTanggal.setText(tblData.getValueAt(tblData.getSelectedRow(), 3).toString());
        edtPukul.setText(tblData.getValueAt(tblData.getSelectedRow(), 4).toString());
        edtRuangan.setText(tblData.getValueAt(tblData.getSelectedRow(), 5).toString());
        edtNamakegiatan.setText(tblData.getValueAt(tblData.getSelectedRow(), 6).toString());

        edtNim.setEditable(false);
        btnSimpan.setText("Ubah");
    }//GEN-LAST:event_tblDataKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SPOI;
    private javax.swing.JLabel SelamatDatang;
    private javax.swing.JLabel Version1;
    private javax.swing.JPanel barangPanel;
    private javax.swing.JPanel bodyPaanel;
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPeralatan;
    private javax.swing.JButton btnRuangan;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JPanel checklistPanel;
    private javax.swing.JComboBox<String> cmbCari;
    private javax.swing.JTextField edtCari;
    private javax.swing.JTextField edtNamakegiatan;
    private javax.swing.JTextField edtNamapeminjam;
    private javax.swing.JTextField edtNim;
    private javax.swing.JTextField edtPukul;
    private javax.swing.JTextField edtRuangan;
    private javax.swing.JTextField edtTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judulBarang;
    private javax.swing.JLabel judulChecklist;
    private javax.swing.JLabel judulPeralatan;
    private javax.swing.JLabel judulRuangan;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblNamauser;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel peralatanPanel;
    private javax.swing.JPanel ruanganPanel;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables
}
