/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.awt.Color;

/**
 *
 * @author HP
 */
//import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public static String nama1;
    public static String nim1;
    public static String jurusan1;
    public static String jk1;
    public static String username1;
    public static String password1;

    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbJk = new javax.swing.ButtonGroup();
        luarPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblJudul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        edtNama = new javax.swing.JTextField();
        lblNim = new javax.swing.JLabel();
        edtNim = new javax.swing.JTextField();
        lblJurusan = new javax.swing.JLabel();
        edtJurusan = new javax.swing.JComboBox<>();
        lblJeniskelamin = new javax.swing.JLabel();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        lblUsername = new javax.swing.JLabel();
        edtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        edtPassword = new javax.swing.JPasswordField();
        lblPassword2 = new javax.swing.JLabel();
        edtPassword2 = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JPanel();
        lblRegister = new javax.swing.JLabel();

        setTitle("REGRISTRASI PENGGUNA");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        luarPanel.setBackground(new java.awt.Color(102, 102, 102));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 0, 0)));
        mainPanel.setPreferredSize(new java.awt.Dimension(732, 448));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconInstiki2.jpg"))); // NOI18N

        lblJudul.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblJudul.setText("Sistem Peminjaman Operasional Instiki");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Account Register");

        lblNama.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNama.setText("Nama Lengkap");

        lblNim.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNim.setText("Nim");

        lblJurusan.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblJurusan.setText("Jurusan");

        edtJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TI-MTI", "TI-DGM", "TI-KAB", "SK" }));

        lblJeniskelamin.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblJeniskelamin.setText("Jenis Kelamin");

        rbLaki.setBackground(new java.awt.Color(255, 255, 255));
        rbJk.add(rbLaki);
        rbLaki.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        rbLaki.setText("Laki - Laki");
        rbLaki.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        rbPerempuan.setBackground(new java.awt.Color(255, 255, 255));
        rbJk.add(rbPerempuan);
        rbPerempuan.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        rbPerempuan.setText("Perempuan");
        rbPerempuan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblUsername.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblUsername.setText("Username");

        lblPassword.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblPassword.setText("Password");

        lblPassword2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblPassword2.setText("Confirm Password");

        btnRegister.setBackground(new java.awt.Color(11, 232, 129));
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegisterMouseExited(evt);
            }
        });

        lblRegister.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconRegister.png"))); // NOI18N
        lblRegister.setText("Register Now");
        lblRegister.setIconTextGap(10);

        javax.swing.GroupLayout btnRegisterLayout = new javax.swing.GroupLayout(btnRegister);
        btnRegister.setLayout(btnRegisterLayout);
        btnRegisterLayout.setHorizontalGroup(
            btnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(btnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnRegisterLayout.createSequentialGroup()
                    .addGap(0, 150, Short.MAX_VALUE)
                    .addComponent(lblRegister)
                    .addGap(0, 149, Short.MAX_VALUE)))
        );
        btnRegisterLayout.setVerticalGroup(
            btnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(btnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblRegister)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lblIcon))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lblJudul)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(349, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(lblNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(323, 323, 323))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblJurusan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblNim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(82, 82, 82))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(lblJeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                                        .addComponent(rbLaki)
                                        .addGap(37, 37, 37)
                                        .addComponent(rbPerempuan)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(edtJurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(edtNim)
                                    .addComponent(edtNama)
                                    .addComponent(edtUsername)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtPassword2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(edtPassword))))
                        .addGap(31, 31, 31))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJudul)
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(edtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNim, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbLaki, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbPerempuan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(edtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );

        javax.swing.GroupLayout luarPanelLayout = new javax.swing.GroupLayout(luarPanel);
        luarPanel.setLayout(luarPanelLayout);
        luarPanelLayout.setHorizontalGroup(
            luarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(luarPanelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        luarPanelLayout.setVerticalGroup(
            luarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(luarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(luarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(luarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseEntered
        // TODO add your handling code here:
        btnRegister.setBackground(new Color(5, 196, 107));
    }//GEN-LAST:event_btnRegisterMouseEntered

    private void btnRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseExited
        // TODO add your handling code here:
        btnRegister.setBackground(new Color(11, 232, 129));
    }//GEN-LAST:event_btnRegisterMouseExited

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        // TODO add your handling code here:

        // Connect Database
        try {
            Class.forName("com.mysql.jdbc.Driver");

            String url = "jdbc:mysql://localhost/db_spoi";
            String username = "root";
            String password = "";

            Connection con;
            con = DriverManager.getConnection(url, username, password);

        // Masuk kedalam Inputannya  
            if (edtNama.getText().equals("") || 
                    edtJurusan.getSelectedItem().equals("") || 
                    edtUsername.getText().equals("") ||
                    rbLaki.getText().equals("") || 
                    edtPassword.getText().equals("")){ 
                JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong", "Validasi Data",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            String nama = edtNama.getText();

            int nim = 0;
            boolean boolNim = true;
            try {
                nim = Integer.parseInt(edtNim.getText());
            } catch (NumberFormatException ex) {
                boolNim = false;
            }
            if (boolNim == false) {
                JOptionPane.showMessageDialog(null, "Mohon isi NIM dengan benar", "Konfirmasi NIM",JOptionPane.INFORMATION_MESSAGE);
                edtNim.requestFocus();
                edtNim.selectAll();
                return;
            }

            String jurusan = (String) edtJurusan.getSelectedItem();

            String jk;
            if (rbLaki.isSelected()) {
                jk = "Laki - Laki";
            } else {
                jk = "Perempuan";
            }
            
            String usernameUser = edtUsername.getText();

            String passwordUser = edtPassword.getText();

            // PENGECEKAN PASSWORD
            if (edtPassword.getText().equals(edtPassword2.getText())) {
                nama1 = edtNama.getText();
                nim1 = edtNim.getText();
                jurusan1 = (String) edtJurusan.getSelectedItem();
                jk1 = rbLaki.getText();
                username1 = edtUsername.getText();
                password1 = edtPassword.getText();

                // go to login
                JOptionPane.showMessageDialog(null, "Registrasi Berhasil", "Registrasi",JOptionPane.INFORMATION_MESSAGE);
                Login lg = new Login();
                lg.setVisible(true);
                lg.pack();
                lg.setLocationRelativeTo(null);
                lg.setDefaultCloseOperation(Register.EXIT_ON_CLOSE);

            } else {
                try {
                    Integer.parseInt(password);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Mohon Konfirmasi Password Anda Dengan Benar", "Password",JOptionPane.INFORMATION_MESSAGE);
                    edtPassword.requestFocus();
                    edtPassword.selectAll();
                    return;
                }
            }

            // STATEMENT 
            Statement stmt;
            stmt = con.createStatement();
            stmt.executeUpdate("INSERT INTO `pengguna`(`nama`, `nim`, `jurusan`, `jeniskelamin`, `username`, `password`) VALUES ('"
                    + nama + "','"
                    + nim + "','"
                    + jurusan + "','"
                    + jk + "','"
                    + usernameUser + "','"
                    + passwordUser + "')");

            edtNama.setText("");
            edtNim.setText("");

            edtJurusan.setSelectedIndex(0);

            edtUsername.setText("");
            edtPassword.setText("");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_btnRegisterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnRegister;
    private javax.swing.JComboBox<String> edtJurusan;
    private javax.swing.JTextField edtNama;
    private javax.swing.JTextField edtNim;
    private javax.swing.JPasswordField edtPassword;
    private javax.swing.JPasswordField edtPassword2;
    private javax.swing.JTextField edtUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblJeniskelamin;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJurusan;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNim;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword2;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel luarPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.ButtonGroup rbJk;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    // End of variables declaration//GEN-END:variables
}
